# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  release:
    types: [published, released]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Build and Push to Humanitec STAGING - Custom Tag
      uses: humanitec/build-push-to-humanitec@image-with-tag-debug
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN_STAGING }}
        organization: robot-kim-org
        humanitec-registry: staging-registry.humanitec.io
        humanitec-api: staging-api.humanitec.io
        tag: mytag
    - name: Build and Push to Humanitec STAGING - Github Tag
      uses: humanitec/build-push-to-humanitec@image-with-tag-debug
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN_STAGING }}
        organization: robot-kim-org
        humanitec-registry: staging-registry.humanitec.io
        humanitec-api: staging-api.humanitec.io
        auto-tag: true
    - name: Build and Push to Humanitec STAGING - Github SHA
      uses: humanitec/build-push-to-humanitec@image-with-tag-debug
      with:
        humanitec-token: ${{ secrets.HUMANITEC_TOKEN_STAGING }}
        organization: robot-kim-org
        humanitec-registry: staging-registry.humanitec.io
        humanitec-api: staging-api.humanitec.io
    - name: Greeting from Kutay
      run: |
        echo "$GITHUB_REF_SLUG $GITHUB_REF_NAME $GITHUB_REF_NAME_SLUG $GITHUB_SHA $GITHUB_REF $kutay1 $kutay2 $kutay3."
    - name: Greeting from Kutay2
      run: |
        echo ${{ env.GITHUB_REF_SLUG }} ${{ env.GITHUB_REF_NAME }} ${{ env.GITHUB_REF_NAME_SLUG }} ${{ env.GITHUB_SHA }} ${{ env.GITHUB_SHA }} ${{ env.GITHUB_REF }} ${{ env.kutay1 }} ${{ env.kutay2 }} ${{ env.kutay2 }} 
        
